[[session]]
name = "tmux config âš™ï¸"
path = "~/.dotfiles/tmux/.config/tmux"
startup_command = "/usr/bin/nvim tmux.conf"

[[session]]
name = "episteme ğŸ“’"
path = "~/public/code/projects/episteme"
startup_command = "/usr/bin/nvim -c 'Telescope find_files'"

[[session]]
name = "friendly-snippets ğŸ“‡"
path = "~/public/code/projects/friendly-snippets"
startup_command = "/usr/bin/nvim -c 'Telescope find_files'"

[[session]]
name = "obsidian ğŸ—’ï¸"
path = "~/public/documents/notes/obsidian-notes"
startup_command = "/usr/bin/nvim -c 'Neotree float'"

[[session]]
name = "stojanow ğŸ‘¨â€ğŸ’»"
path = "~/public/code/projects/stojanow.com"
startup_command = "/home/piotr/.local/bin/tmux-startup-dev"
